{{- $fullName := include "vulpine.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vulpine.fullname" . }}
  labels:
    {{- include "vulpine.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "vulpine.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vulpine.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vulpine.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.server.env }}
          env:
            {{- toYaml .Values.server.env | nindent 12 }}
          {{- end }}
          command: ["/bin/vulpine"] 
          args:
            - -ecrImageRegistry={{ .Values.server.ecrimageregistry }}
            - -ecrProfile={{ .Values.server.ecrprofile }}
            - -interval={{ .Values.server.interval }}
            - -mode={{ .Values.server.mode }}
            - -repoTag={{ .Values.server.repotag }}
            - -scanTarget={{ .Values.server.scantarget }}
            {{- if .Values.server.extraArgs }}
              {{- toYaml .Values.server.extraArgs | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: 10
            periodSeconds: 120
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: 10
            periodSeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
